[devent]

# the name of the devent
name="IPFS Camp"

# where the event is happening
location="Convento do Beato, Lisbon, Portugal"

# the dates the devent runs
dateStart = "2022-10-28"
dateEnd = "2022-10-30"

# a pithy tag line you want to show in the "hero/splash" part of the landing page
tagline="""
IPFS Camp 2022  is a gathering for the entire  IPFS community: devs, operators, implementers,  researchers – and you!
"""

description="""
Join us for talks, workshops, discussion circles, hacking time, and more, all focused on celebrating and advancing IPFS.
"""


# a link to the devent website (what domain do you expect to use?)
link="https://2022.ipfs.camp/"

# a link to get tickets
ticketLink="https://lu.ma/ipfscamp22"

# a link to RSVP for the event
# rsvpLink="https://lu.ma/ipfscamp22"

# a link to apply to speak for the event
speakLink="https://airtable.com/shrOxmXUqwojf0Bjj"

# a link to the recap and videos
# recapLink="https://blog.ipfs.io/ipfs-ping-2022-recap/"

# a link to a logo image for the event
logo="ipfs-camp-logo.svg"

# a link to a large res image for the hero/splash background.
# you likely want to use the devent location/city or something meaningful to the community
bgimg="tree-mandala.png"

# the organizers of the devent (usually a group)
org="the IPFS Project"

# the website of the organizers
orglink="https://ipfs.tech"

# url for this event repo
repo="https://github.com/pathfindertools/ipfs-camp-2022"

# Header Navigation
# [
#   ["Item 1", "#item1"],
#   ["Item 2", "#item2"],
# ]
navigation = [
  ["About IPFS", "./#about" ],
  ["Tracks", "./#tracks" ],
  ["Tickets", "./#tickets" ],
  ["Schedule", "./#schedule" ],
  ["Speakers", "./#speakers" ],
  ["FAQ", "./#faq" ],
]

# list the participating teams.
# the format here is:
# [
#   ["Team Name", "https://team.org", "https://team.org/team-logo.jpg"],
# ]
teams = [
  ["Protocol Labs", "https://protocol.ai", "https://media.graphassets.com/e8bIG2apSUauy2dqK35W" ],
  ["Consensus Lab", "http://consensus-lab.com/", "./teams/consensus-lab.png" ],
  ["Filecoin Foundation", "https://fil.org/", "./teams/filecoin-foundation.png" ],
  ["IPFS", "https://ipfs.io", "./teams/ipfs.jpeg" ],
  ["Spaceport", "", "./teams/spaceport.jpeg" ],
  ["PL Launchpad", "https://pl-launchpad.io", "./teams/pl-launchpad.png" ],
  ["LibP2P", "", "./teams/libp2p.png" ],
  ["Drand", "", "./teams/drand.png" ],
  ["Lotus", "", "./teams/lotus.jpeg" ],
  ["Compute Over Data", "", "./teams/compute-over-data.png" ],
  ["Talent Protocol", "", "./teams/talent-protocol.png" ],
]

# this is a Frequently Asked Questions section.
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[faq]
"What is IPFS Camp 2022?" = """
IPFS Camp 2022 is a gathering for the entire IPFS community: builders, operators, researchers… and you! There will be talks, workshops, discussion circles, hacking time, and more — all focused on celebrating and advancing IPFS. 
"""
"Who is it for? Why should I attend?" = """
IPFS Camp is for everyone who would like to build the Distributed Web together. The 3-day event is designed for a broad range of interests and experience via multiple, parallel tracks. You can expect to…
    - Meet IPFS creators, maintainers, builders & operators
    - Learn about progress & plans for IPFS & libp2p
    - Join discussions and workshops on key goals and challenges
    - Share your work in building the Distributed Web
    - Learn how you can contribute to IPFS & grow your own IPFS-based projects
"""
"Sounds great! How do I participate?" = """
If you don’t have a ticket yet, head to the Tickets section to purchase a ticket or apply for a discounted one.

This is a decentralized event, with over 15 tracks across 3 days. Explore the track descriptions and schedules, and choose your own adventures depending on your interests! 

We’re keen to showcase builders, users, and ideas from across the community. If you’re interested in giving a talk, sharing your work, or leading a new track, please Apply to Speak.
This is a decentralized event, with over 15 tracks across 3 days. Explore the track descriptions and schedules, and choose your own adventures depending on your interests! 
"""    
"What does the ticket include?" = """
All tickets include entry to the full 3-day event and coffee, pastries, lunch, and dinner at the IPFS Camp venue. 
"""
"Can I organize a side event?" = """    
Yes! Please reach out to camp@ipfs.io if you’d like to discuss listing it on this website.
"""    
"What's the COVID policy?" = """    
It has been almost three years since our last in-person IPFS Camp! We’re excited to see everyone’s faces soon! While COVID-19’s most acute days are past, we are taking precautions to help limit spread and protect the health of our IPFS and global communities.
As of September 2022, Portugal has lifted entry requirements related to COVID-19.

RAPID ANTIGEN TESTING: IPFS Camp will host a 100% free mobile testing site at the entrance to Convento do Beato where every attendee will be required to take an antigen rapid test prior to picking up their badge (regardless of vaccination status).
Tests will be self administered, and results take about 15 minutes to process. 

MASKS: IPFS Camp will have plenty of masks and hand sanitizer available at the entrance and key locations within the venue each day. We recommend wearing a mask indoors.

MEALS: Lunch and dinner will primarily take place in well-ventilated areas or outdoors.

ILLNESS: If you feel sick or have tested positive, stay at home. If at any point during your visit to IPFS Camp you feel sick, please visit our onsite testing center to take a follow-up test. Whether or not you test positive for COVID-19, if you have symptoms that mirror any other communicable disease (i.e. flu, cold, etc.) we ask that you do not visit in-person venues until your symptoms subside. 

If you must cut short your visit to IPFS Camp due to illness, you may email camp@ipfs.io for a ticket refund. We will be sorry to see you go but thankful for your part in keeping the community healthy.
"""
"How do I reach the organizers" = """    
Please reach out to camp@ipfs.io with any questions or suggestions.
"""

# Speaker Items
#
# the format is:
# [[speakers]]
# name = "Speaker Name"
# company = "Company"
# image = "image.jpg"

[[speakers]]
name = "Marta Evans"
company = "Protocol Labs"
image = "speakers/marta-evans.jpg"
[[speakers]]
name = "George Lory"
company = "Protocol Labs"
image = "speakers/george-lory.jpg"
[[speakers]]
name = "Jerry Church"
company = "Protocol Labs"
image = "speakers/jerry-church.jpg"
[[speakers]]
name = "Marta Evans"
company = "Protocol Labs"
image = "speakers/marta-evans.jpg"
[[speakers]]
name = "George Lory"
company = "Protocol Labs"
image = "speakers/george-lory.jpg"
[[speakers]]
name = "Jerry Church"
company = "Protocol Labs"
image = "speakers/jerry-church.jpg"
[[speakers]]
name = "Marta Evans"
company = "Protocol Labs"
image = "speakers/marta-evans.jpg"
[[speakers]]
name = "George Lory"
company = "Protocol Labs"
image = "speakers/george-lory.jpg"
[[speakers]]
name = "Jerry Church"
company = "Protocol Labs"
image = "speakers/jerry-church.jpg"
[[speakers]]
name = "Marta Evans"
company = "Protocol Labs"
image = "speakers/marta-evans.jpg"
[[speakers]]
name = "George Lory"
company = "Protocol Labs"
image = "speakers/george-lory.jpg"

# Ticket Items
#
# [[tickets]]
# name = "General"
# price = "($400)"
# description = "The essential ticket for attending IPFS Camp 2022. This is for everyone!"
# linkLabel = "Purchase General Ticket"
# link = "#"

[[tickets]]
name = "General"
price = "($400)"
description = "The essential ticket for attending IPFS Camp 2022. This is for everyone!"
linkLabel = "Purchase General Ticket"
link = "#"
[[tickets]]
name = "Builder"
price = "($200)"
description = "Discounted tickets for builders: anyone who is building with IPFS or related technologies, or contributing to IPFS project or community."
linkLabel = "Purchase Builder Ticket"
link = "#"
[[tickets]]
name = "Student & Academic"
price = "($100)"
description = "Limited tickets for students, educators and researchers with academic affiliation and experience or interest in IPFS."
linkLabel = "Apply for Academic Ticket"
link = "#"
[[tickets]]
name = "Volunteer"
price = "(Free)"
description = "Limited tickets for community members who can volunteer for 3 x 2 hour shifts during the event."
linkLabel = "Apply for Volunteer Ticket"
link = "#"
[[tickets]]
name = "IPFS Scholars"
price = "(Free)"
description = "This program provides entry, flights, and accommodation for individuals from underrepresented communities, unique circumstances, or developing areas to connect with and contribute to the IPFS ecosystem."
linkLabel = "Apply to IPFS Scholars Program"
link = "#"

# Track Items
#
# [[tracks]]
# name = "Content Routing"
# date = "28-29 Oct"
# description = "Approaches and protocols to content routing in IPFS, what we've learned so far, and talks about possible directions for the future."
# link = "#"
[[tracks]]
name = "Data Transfer"
date = "28-29 Oct"
description = "Getting and sending content. Moving data across the wire. State and evolution of transferring data across the interplanetary stack."
link = "#"
[[tracks]]
name = "Compute over Data"
date = "28-29 Oct"
description = "Producing data without leaving the Merkle Forest -- How do we do it?  How do we make it manageable at scale?  How do we make the results useful and discoverable?  In this track, see what others are up to, and share your own dreams!"
link = "#"
[[tracks]]
name = "Libp2p day"
date = "28-29 Oct"
description = "The first ever libp2p Day: a gathering for libp2p builders, contributors, and maintainers!"
link = "#"
[[tracks]]
name = "IPFS for Creatives"
date = "28-29 Oct"
description = "Calling all creators! This is the first ever IPFS sponsored track for content creators (and supporters!) of all types. Come meet other creatives, learn from other artists and experts in the web3 space, and be one of the first to join our growing community."
link = "#"
[[tracks]]
name = "IPFS Implementations"
date = "28-29 Oct"
description = "A wave of new IPFS implementations has grown in the past year. Meet the teams taking IPFS to the next level and find your on-ramp to working on the protocol."
link = "#"
[[tracks]]
name = "Growing with IPFS"
date = "28-29 Oct"
description = "Contributing, building, funding, grants, accelerators, decentralized job fair, and more ways to get involved."
link = "#"
[[tracks]]
name = "Learning IPFS 101"
date = "28-29 Oct"
description = "A hands on session on getting started with IPFS, including what it is, how to set up an IPFS node, CLI commands, pinning, gateways and more. If you've been wanting to try out IPFS - now's your chance!"
link = "#"
[[tracks]]
name = "IPFS Apps for Fun & Awesome"
date = "28-29 Oct"
description = "A highlights reel of the most exciting and useful user and developer tools for IPFS."
link = "#"
[[tracks]]
name = "IPFS 201: Design Patterns & Developer Tools"
date = "28-29 Oct"
description = "Workshops, demos, and an expert panel covering IPFS app architectures, developer tools design patterns, developer experience and everything you need to know to build and deploy robust production-grade content-addressed apps."
link = "#"
[[tracks]]
name = "Measurement & Performance"
date = "28-29 Oct"
description = " A data-driven approach to the design and operation of IPFS and libp2p through rigorous network measurements, performance evaluation and recommendations for builders and operators."
link = "#"
[[tracks]]
name = "libp2p Privacy"
date = "28-29 Oct"
description = "Dive into the current privacy work happening on libp2p and get the chance to provide feedback on direction and next steps and hear from experts in the field."
link = "#"
[[tracks]]
name = "Gaming, Metaverse, & Video"
date = "28-29 Oct"
description = "Demos of how IPFS can save bandwidth and increase flexibility. Talks about directions for the future."
link = "#"
[[tracks]]
name = "Browsers"
date = "28-29 Oct"
description = "Learn the current status, ongoing challenges, and upcoming work to integrate IPFS and related technologies into browsers and the web itself."
link = "#"
[[tracks]]
name = "Decentralized Job Fair"
date = "28-29 Oct"
description = "Whether you are looking for a new role or simply want to learn more about open source projects that you can contribute to, this decentralized job fair is the place to be."
link = "#"
[[tracks]]
name = "IPFS Operators & Enterprise"
date = "28-29 Oct"
description = "Explore applications & deployments of IPFS in large scale cloud & enterprise use cases with talks from IPFS operators about their experiences and best practices."
link = "#"

# Tracks Section
# Hide propose button by commenting out
#
[tracksSection]
title="Tracks"
proposeLink="#"
proposeLabel="Propose a Track"

# schedule section
[schedule]
description="""
"""

# this is a footer section, with any footer links you may want.
# there are three sections: links (general), legal (policy + terms), and social.
[footer]

[footer.links]
"Protocol Labs" = "https://protocol.ai/"
"Event Github" = "https://github.com/protocol/labweek-2022"

[footer.legal]
"Privacy Policy" = "#"
"Terms & Conditions" = "#"

[footer.social]
twitter = "ipfs"
github = "ipfs"
