[devent]

# the name of the devent
name="LabWeek22"

# where the event is happening
location="Lisbon, Portugal"

# the dates the devent runs
dateStart = "2022-10-20"
dateEnd = "2022-11-4"

# a pithy tag line you want to show in the "hero/splash" part of the landing page
tagline="""
A decentralized conference hosted by Protocol Labs
"""

description="""
The Protocol Labs Network is hosting our first ever decentralized conference in Lisbon. Teams in the network will spin up dozens of events across Oct 22-Nov 4. These will take many forms, from summits to unconferences to networking happy hours, and cover a wide array of topics, including decentralized storage, public goods funding, cryptoeconomics, DeSci, and many more. Then you get to choose your own adventure for which ones to attend to make the biggest impact. 

We invite you to join us as we drive breakthroughs in computing to push humanity forward.
"""


# a link to the devent website (what domain do you expect to use?)
link="https://labweek22.on.fleek.co"

# a link to RSVP for the event
rsvpLink="https://airtable.com/shrsicDt1IpeIKVIg"

# a link to the recap and videos
# Dependent on https://github.com/ipfs/ipfs-blog/issues/443 first.
# recapLink="https://blog.ipfs.io/ipfs-ping-2022-recap/"

# a link to a logo image for the event
logo="ipfs-thing-logo.png"

# a link to a large res image for the hero/splash background.
# you likely want to use the devent location/city or something meaningful to the community
bgimg="harpa.jpg"

# the organizers of the devent (usually a group)
org="Protocol Labs"

# the website of the organizers
orglink="https://protocol.ai"

# url for this event repo
repo="https://github.com/pathfindertools/labweek-2022"

# list the participating teams.
# the format here is:
# [
#   ["Team Name", "https://team.org", "https://team.org/team-logo.jpg"],
# ]
teams = [
  ["Number Zero", "", "https://bafybeicftvbmvctgso22rtgvx43bql3g55p3x4a25bfnfkqqv3nwyfzewq.ipfs.dweb.link/number-zero-logo.png" ],
  ["Protocol Labs", "https://protocol.ai", "https://media.graphassets.com/e8bIG2apSUauy2dqK35W" ],
  ["PL Research", "https://research.protocol.ai", "https://research.protocol.ai/images/pl_research_logo.svg" ],
  ["Fission", "https://fission.codes", "https://kit.fission.app/images/logo-dark-colored.svg" ],
  ["Ceramic", "https://ceramic.network", "https://user-images.githubusercontent.com/3909429/177210536-e0834b0f-e313-456f-8bf5-1e5f27b0898a.png" ],
  ["Fluence", "https://fluence.network", "https://gateway.pinata.cloud/ipfs/QmY1iFhZ6Lde3Tpcwd7ygEDPSJfPuSyGV97iiH2VEj16jB" ],
]

# this is a Frequently Asked Questions section.
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[faq]

"What is LabWeek22" = """
  Protocol Labs drives breakthroughs in computing to push humanity forward.‌ Together, teams in the network have developed web3 projects like IPFS, Filecoin, and libp2p, and we have ambitious goals to continue to transform and improve computing and the decentralized web.
"""

# schedule section config
[schedule]
description="""
All scheduled events are [optional](/#faq).
"""

# this is a footer section, with any footer links you may want.
# there are three sections: links (general), legal (policy + terms), and social.
[footer]

[footer.links]
"IPFS" = "https://ipfs.io"
"Event Github" = "https://github.com/pathfindertools/labweek-2022"

[footer.legal]
"Privacy Policy" = "#"
"Terms & Conditions" = "#"

[footer.social]
twitter = "ipfs"
github = "ipfs"
