# the name of your event
name = "IPFS þing Opening"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@jbenet"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
# website = ""

# the start date of the event
date = "2022-07-12"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 12:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "150"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
color="orange"

# a description of the event.
# will show up when the user clicks the event card.
description = """
A few short talks introducing the IPFS þing week, how it will work, & what to expect.
"""

[[timeslots]]
startTime="09:00"
speakers=[]
title="Meet & Greet"
description=""

[[timeslots]]
startTime="09:20"
speakers=[]
title="Welcome & Introductions"
description=""

[[timeslots]]
startTime="10:30"
speakers=[]
title="IPFS þing Intro and Q&A"
description=""

[[timeslots]]
startTime="11:00"
speakers=["@jbenet"]
title="Kickoff Keynote"
description=""

