# the name of your track or event
name = "Project & Community"

# the name of the group organizing the event
org = ""

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@mishmosh"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://discuss.ipfs.io/t/2022-07-15-project-community/14637"

# the start date of the event
date = "2022-07-15"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 12:30"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Discussions"]

# a color, to group key events visually. use sparingly
color="cyan"

# a description of the track.
# will show up when the user clicks the event card.
description = """

This track aims to create space for advancing the IPFS project and community. New session proposals are welcome, especially those that focus on a specific, actionable subtopic rather than attempting to grapple with the entire universe of project and community stewardship at oncev.

"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
#
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots

[[timeslots]]
startTime="09:00"
speakers=["@mishmosh"]
title="Welcome standup discussion"
description="A brief introduction to the track"

[[timeslots]]
startTime="09:15"
speakers=["@lidel"]
title="InterPlanetary Improvement Process (IPIP)"
description="A walkthrough of the new IPIP (RFC-like) process and its motivations, updated specs repository, and when and why you should submit an IPIP. Q&A at the end."

[[timeslots]]
startTime="09:45"
speakers=["@autonome"]
title="Shaping IETF and W3C Standards"
description="Discuss evolving web-wide standards & specs that might benefit from participation from our community. Examples include upcoming deadline at IETF for multi* stuff started long ago, and W3C activity around extensions APIs and webviews and wallet APIs."

[[timeslots]]
startTime="10:15"
speakers=["@bmann"]
title="Content Addressing Alliance"
description="IPFS has 'won'. Content addressing is a sustaining innovation that can make its way into many more places. Discuss creating a cross-organization Content Addressable Alliance that advocates and promotes the usage of content addressing."

[[timeslots]]
startTime="10:45"
speakers=[""]
title="Break"
description=""

[[timeslots]]
startTime="11:00"
speakers=["@autonome, @mishmosh, @jbenet"]
title="Funding IPFS Implementations"
description="Brief session on history of funding IPFS implementations, and exciting updates going forward."

[[timeslots]]
startTime="11:30"
speakers=["@biglep"]
title="A month in PL EngRes IPFS Development and how you can be involved"
description="Learn what happens in a given month in IPFS development for projects like Kubo, js-ipfs, and supporting the wider community.  You should walk away with better insight into venues you can engage the maintainers and ideas/input will be welcome as well."

[[timeslots]]
startTime="11:45"
speakers=["@galargh"]
title="GitHub Configuration (of IPFS organization) as Code"
description="This session will be a walk through how PL manages IPFS GitHub organization configuration as code using a tool called GitHub Management. It'll provide practical information on how to request changes to the configuration (for example, if you contribute frequently to a repository within IPFS and you'd want to become a collaborator) and how to set up a similar solution in any other GitHub organization."

[[timeslots]]
startTime="12:00"
speakers=["@b5"]
title="Mutual Therapy Session for operators, maintainers, founders, or ceos"
description="A self-explanatory roundtable."

