# the name of your event
name = "IPFS þing Closing"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@jbenet"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
# website = ""

# the start date of the event
date = "2022-07-16"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "16:00 - 18:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "300"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
color="orange"

# a description of the event.
# will show up when the user clicks the event card.
description = """
A sequence of closing keynotes summarizing the week and
looking ahead to the rest of 2022 and 2023.
"""
