# the name of your track or event
name = "Building Apps on IPFS"

# the name of the group organizing the event
org = ""

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@bmann"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://discuss.ipfs.io/t/building-apps-on-ipfs-track/14605"

# the start date of the event
date = "2022-07-13"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 16:30"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """

From Developer Experience to User Experience, how do we build full apps on IPFS? What are the goals of IPFS beyond infrastructure?

Select events to join and follow in the IPFS Discourse https://discuss.ipfs.io/t/2022-07-13-building-apps-on-ipfs-track/14605

"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="09:00"
speakers=["@bmann"]
title="Track Intro: Building Apps on IPFS"
description="Can we make IPFS the protocol a default deployment target like Vercel or Netlify? What does apps on IPFS even mean? Does data portability itself on IPFS something that can be added to any apps? Open discussion, bring your thoughts! Track intro event is on the main notes page https://discuss.ipfs.io/t/building-apps-on-ipfs-track/14605"

[[timeslots]]
startTime="9:30"
speakers=["@expede", "@ianopolous", "@smrz2001"]
title="Identity, Capabalities, & Private Data"
description="9:30am - 11am. @expede - Fission Webnative SDK: DIDs, UCANs & WNFS, @ianopolous PeerGos architecture, @smrz2001 Ceramic, CACAO, DID Session Keys. 3 short 15min overviews followed by 45min of discussion on working together."

[[timeslots]]
startTime="12:00"
speakers=["@cdata"]
title="Subconscious & Noosphere: WWW over IPFS"
description="Subconscious is a tool for thought with the goal of fostering a credibly unowned, globally-distributed knowledge graph. Noosphere is the IPFS-adjacent protocol that drives Subconscious. In this session we will discuss the opportunities and challenges that led us to using IPFS, and detail some of the designs we are implementing to serve requirements in naming, authz and network availability. Event on IPFS Discourse https://discuss.ipfs.io/t/subconscious-noosphere-www-over-ipfs/14652"

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch Break"
description=""

[[timeslots]]
startTime="14:00"
speakers=["@b5"]
title="Application space in IPFS"
description="this talk will explore tensions in the design of IPLD, multicodecs, and UnixFS, and an opportunity to open up a new class of application development on IPFS by re-orienting toward arbitrary metadata & a WASM runtime"

[[timeslots]]
startTime="15:00"
speakers=["@evgenyponomarev, @aronchick"]
title="Compute + IPFS"
description="The Compute Over Data Working Group is just getting started. We'll have intros from WG members on their compute solutions and how they intersect with IPFS, and how they see powering appss."

[[timeslots]]
startTime="16:00"
speakers=["@bmann"]
title="Wrap Up Session"
description="Come together and review all issues and points of discussion harvested during the day. Assign follow ups, working group creation, and other connections as needed (aim for 30min)"


