# the name of your track or event
name = "Aqua and IPFS"

# the name of the group organizing the event
org = "Fluence Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@evgenyponomarev"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://ipfs-althing.io"

# the start date of the event
date = "2022-07-14"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "14:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "20"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """

Aqua is a programming language and a runtime for distributed algorithms based on Ï€-calculus. Aqua creates secure, ad-hoc overlay networks for every execution making easy to iterate on deploying, testing, and upgrading permissionless p2p protocols.

Come to learn about Aqua and discuss with us how it can help improving IPFS.

"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="14:00"
speakers=["@alari"]
title="Aqua language intro"

[[timeslots]]
startTime="14:30"
speakers=["@folex"]
title="Workshop. Domain-specific IPFS content indexer with Aqua"

[[timeslots]]
startTime="15:30"
speakers=["@mikevoronov"]
title="AquaVM: calculus based VM for distributed algorithms"

[[timeslots]]
startTime="16:15"
speakers=["@mikevoronov"]
title="AquaVM: convergence model with CRDT for decentralized networks"

