# the name of your track or event
name = "Growing With IPFS"

# the name handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "James Tunningley"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 13:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Panels", "Q&A"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Learn about how to grow your skills and/or your project with IPFS! We'll cover contributing, building, open source grants, accelerators, funding, and more ways to get involved.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="09:00"
speakers=["@speaker_name", "@other_speaker_name"]
title="Welcome standup discussion"
description=""

[[timeslots]]
startTime="10:00"
speakers=["James Tunningley"]
title="Welcome Remarks"
description=""

[[timeslots]]
startTime="10:10"
speakers=["Daniel Norman"]
title="Turning your IPFS ideas into reality as a builder"
description=""

[[timeslots]]
startTime="10:30"
speakers=["Niki Gokani, Erin OConnor, Dawn Kelly"]
title="Getting started: Hackathons & Grants"
description=""

[[timeslots]]
startTime="10:50"
speakers=["Nandit Mehra"]
title="Succeeding with IPFS with the Founder of Lighthouse"
description=""

[[timeslots]]
startTime="11:15"
speakers=[]
title="Coffee Break"
description=""

[[timeslots]]
startTime="11:30"
speakers=["Ruben"]
title="Beyond Hackathons: Making your startup a reality (Accelerators & Investment)"
description=""

[[timeslots]]
startTime="11:55"
speakers=["Lacey (moderator), Shaun Johnson (Tachyon), Carlos Silva (Faber)"]
title="[Panel] Investing, Web3 Business Models & Failcon"
description=""

[[timeslots]]
startTime="12:30"
speakers=[]
title="How to get hired in the ecosystem"
description=""

[[timeslots]]
startTime="12:45"
speakers=["James Tunningley + key PL speakers, i.e. Daniel, Sonia, Erin, Ruben, Lacey, tbc talent POC"]
title="Open Q&A (Growing with IPFS Track)"
description=""