# the name of your track or event
name = "IPFS 201: App Design Patterns and Developer Tools"

# the name handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Daniel Norman"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Intermediate"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Workshops", "Talks", "Demos", "Panels"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Workshops, demos, and an expert panel covering IPFS app architectures, developer tools, design 
  patterns and everything you need to know to build and deploy robust 
  production-grade apps using IPFS.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="10:00"
speakers=["Daniel Norman"]
title="Track introduction"
description="Dapps are all the rave, but there's no consensus about how they should be built. \n\n There's a cambrian explosion of developer tools and many emerging design patterns using IPFS. This introduction will set the stage for some of the fantastic speakers we have during the day who'll be sharing the state of the art in app design patterns and developer tools."

[[timeslots]]
startTime="10:20"
speakers=["Boris Mann"]
title="Fission & The WebNative SDK"
description=""

[[timeslots]]
startTime="10:50"
speakers=["Carson Farmer"]
title="Introduction to Tableland"
description=""

[[timeslots]]
startTime="11:20"
speakers=[]
title="☕️ Break"
description=""

[[timeslots]]
startTime="11:30"
speakers=["Alex Potsides"]
title="Debugging js-ipfs and js-libp2p Like a Pro"
description="The lead maintainer of js-ipfs and js-libp2p will share tips and tricks for debugging js-ipfs"

[[timeslots]]
startTime="12:05"
speakers=["Brendan O'Brien (b5)", "Brooklyn Zelenka", "Carson Farmer", "Sara Feenan"]
title="Panel: State of the IPFS DevTools ecosystem"
description=""

[[timeslots]]
startTime="12:45"
speakers=["Mauve Signweaver"]
title="What is IPLD Anyway?"
description="This talk will go over what IPLD is, how lenses like Schemas and Advanced Data Layouts work, and why they could be useful for your application."

[[timeslots]]
startTime="13:00"
speakers=[""]
title="Lunch 🍱🍔"
description=""

[[timeslots]]
startTime="14:00"
speakers=["Lidel"]
title="Using the DAG API to efficiently fetch geoip data with IPFS"
description="An overview of how the [ipfs-geoip](https://github.com/ipfs-shipyard/ipfs-geoip) library works and the recent refactor to use the DAG API."

[[timeslots]]
startTime="14:15"
speakers=["Horacio Herrera"]
title="Local-First, Multi-Device Applications With IPFS"
description="In this talk, we'd like to share the ideas and technical approaches we came up with while building [Mintter](https://mintter.com/) on top of IPFS for the past 2.5 years. Some of the challenges we faced didn’t have easy, or plug-and-play solutions at the time, such as multi-device, decentralized identity, version control, etc. Mintter is a hypertext system for knowledge management in open discussion groups. While working on the product, we were greatly inspired by the work of the founding fathers of hypertext: Doug Engelbart, Ted Nelson and others."

[[timeslots]]
startTime="14:40"
speakers=["Chris Anderson", "David Choi", "Alan Shaw"]
title="UCAN Build Apps with IPFS"
description="Learn how content addressed user-centric protocols like IPFS, [DID](https://www.w3.org/TR/did-core/), and [UCAN](https://ucan.xyz/) will change the web, and how to build Node.js applications using them. \n\n The [web3.storage](https://web3.storage/) team will share the latest APIs and walk you through building your own application data model. Start with DID-based self-sovereign auth, a great opportunity to learn about the next wave of digital identity, and write code to upload files as well as JSON objects. They'll discuss IPFS data structures like IPLD trees and graphs, and how they can be used in applications."

[[timeslots]]
startTime="15:30"
speakers=[]
title="☕️ Break"
description=""

[[timeslots]]
startTime="15:45"
speakers=["Hector Sanjuan"]
title="State without consensus: introduction to Merkle-CRDTs on IPFS"
description="Merkle-DAGs are fun, but even more  when they can be used to compute an ever-evolving state (i.e. a database) collaboratively maintained by a set of peers that may come and go as they please. Join us to learn about Merkle-CRDTs, what use-cases they fit and how they power things like IPFS Cluster pinset distribution."

[[timeslots]]
startTime="16:15"
speakers=["Manfred Touron"]
title="What's next for the Berty Protocol"
description="Most people aware of Berty won't know that we've made an underlying protocol that could power many other projects. We want to change that and help more builders to create powerful dApps. Let's look at what problems we're addressing and how."

[[timeslots]]
startTime="16:35"
speakers=[""]
title="TBD"
description=""