# the name of your track or event
name = "IPFS 101 / User Apps on IPFS"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "DeveloperAlly"

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Beginner"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  a hands on session on getting started with IPFS, including what it 
  is, how to set up an IPFS node, CLI commands, pinning, gateways and more. 
  If you've been wanting to try out IPFS - now's your chance!
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="13:00"
speakers=["Ryan Baumann"]
title="Breaking Free of the Client-Server Model with IPFS"
description=""

[[timeslots]]
startTime="13:30"
speakers=["Lindsay Walker"]
title="Hands On with IPFS - Installing, using the CLI and implementing kubo in a boilerplate app"
description=""

[[timeslots]]
startTime="14:45"
speakers=["Hugo Valtier (Jorropo)"]
title="Why Build on IPFS?"
description=""

[[timeslots]]
startTime="15:00"
speakers=[]
title="Skiff - web3 email, drive & docs"
description=""

[[timeslots]]
startTime="15:30"
speakers=[]
title="Huddle01"
description=""

[[timeslots]]
startTime="16:00"
speakers=[]
title="Openlinks - web3 Linktree"
description=""

[[timeslots]]
startTime="16:15"
speakers=[]
title="Portrait.gg"
description=""

[[timeslots]]
startTime="16:30"
speakers=[]
title="NIMI.eth"
description=""

[[timeslots]]
startTime="16:45"
speakers=[]
title="Endless Jewellery"
description=""

[[timeslots]]
startTime="16:55"
speakers=[]
title="Wrap up"
description=""
