# the name of your event
name = "Choose Your Icelandic Adventure"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@yunigraham"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://lu.ma/community/com-XnCETb7tjO4jV3N/calendar"

# the start date of the event
date = "2022-07-17"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "varies"

# the event venue name (will show up on the event card - TODO)
venueName = "multiple"

# the event venue address (will show up on a map -- TODO)
venueAddress = "multiple"

# the max number of attendees of the event
attendees = "varies"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Social", "Outing", "Adventure", "Fun"]

# a color, to group key events visually. use sparingly
color="slate"

# a description of the event.
# will show up when the user clicks the event card.
description = """
We have arranged many exciting opportunities for you to experience in Iceland. Choose from the following adventures:
E-Bike: https://lu.ma/ipfsthing-geobike-17
Glacier Walk: https://lu.ma/ipfsthing-glacier-17
Horseback Riding: https://lu.ma/ipfsthing-horses-17
Into the Volcano: *https://lu.ma/ipfsthing-volcanos-17
Golden Circle: *https://lu.ma/ipfsthing-gc-17
"""
