# the name of your event
name = "Closing Dinner @ Borg Restaurant"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@yunigraham"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://lu.ma/ipfsthing-borgdinner-16"

# the start date of the event
date = "2022-07-16"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "19:00 - 22:00"

# the event venue name (will show up on the event card - TODO)
venueName = "Borg Restaurant"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Pósthússtræti 11, 101 Reykjavík, Iceland"

# the max number of attendees of the event
attendees = "100"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Dinner"]

# a color, to group key events visually. use sparingly
color="indigo"

# a description of the event.
# will show up when the user clicks the event card.
description = """
​We are closing this thing out in style - art deco to be exact! This is the last organized dinner of IPFS Thing 2022. Thank you so much for coming all the way to Reykjavik for the advancement of all things IPFS ...see what I did there?

We are looking forward to seeing you there!
"""
